using System;

namespace Unique.Engine
{
    public enum Keycode
    {
        UNKNOWN = 0,

        RETURN = '\r',
        ESCAPE = 27,
        BACKSPACE = '\b',
        TAB = '\t',
        SPACE = ' ',
        EXCLAIM = '!',
        QUOTEDBL = '"',
        HASH = '#',
        PERCENT = '%',
        DOLLAR = '$',
        AMPERSAND = '&',
        QUOTE = '\'',
        LEFTPAREN = '(',
        RIGHTPAREN = ')',
        ASTERISK = '*',
        PLUS = '+',
        COMMA = ',',
        MINUS = '-',
        PERIOD = '.',
        SLASH = '/',
        D0 = '0',
        D1 = '1',
        D2 = '2',
        D3 = '3',
        D4 = '4',
        D5 = '5',
        D6 = '6',
        D7 = '7',
        D8 = '8',
        D9 = '9',
        COLON = ':',
        SEMICOLON = ';',
        LESS = '<',
        EQUALS = '=',
        GREATER = '>',
        QUESTION = '?',
        AT = '@',
        /*
           Skip uppercase letters
         */
        LEFTBRACKET = '[',
        BACKSLASH = '\\',
        RIGHTBRACKET = ']',
        CARET = '^',
        UNDERSCORE = '_',
        BACKQUOTE = '`',
        A = 'a',
        B = 'b',
        C = 'c',
        D = 'd',
        E = 'e',
        F = 'f',
        G = 'g',
        H = 'h',
        I = 'i',
        J = 'j',
        K = 'k',
        L = 'l',
        M = 'm',
        N = 'n',
        O = 'o',
        P = 'p',
        Q = 'q',
        R = 'r',
        S = 's',
        T = 't',
        U = 'u',
        V = 'v',
        W = 'w',
        X = 'x',
        Y = 'y',
        Z = 'z',

        CAPSLOCK = Scancode.SCANCODE_CAPSLOCK | (1 << 30),

        F1 = Scancode.SCANCODE_F1 | (1 << 30),
        F2 = Scancode.SCANCODE_F2 | (1 << 30),
        F3 = Scancode.SCANCODE_F3 | (1 << 30),
        F4 = Scancode.SCANCODE_F4 | (1 << 30),
        F5 = Scancode.SCANCODE_F5 | (1 << 30),
        F6 = Scancode.SCANCODE_F6 | (1 << 30),
        F7 = Scancode.SCANCODE_F7 | (1 << 30),
        F8 = Scancode.SCANCODE_F8 | (1 << 30),
        F9 = Scancode.SCANCODE_F9 | (1 << 30),
        F10 = Scancode.SCANCODE_F10 | (1 << 30),
        F11 = Scancode.SCANCODE_F11 | (1 << 30),
        F12 = Scancode.SCANCODE_F12 | (1 << 30),

        PRINTSCREEN = Scancode.SCANCODE_PRINTSCREEN | (1 << 30),
        SCROLLLOCK = Scancode.SCANCODE_SCROLLLOCK | (1 << 30),
        PAUSE = Scancode.SCANCODE_PAUSE | (1 << 30),
        INSERT = Scancode.SCANCODE_INSERT | (1 << 30),
        HOME = Scancode.SCANCODE_HOME | (1 << 30),
        PAGEUP = Scancode.SCANCODE_PAGEUP | (1 << 30),
        DELETE = 127,
        END = Scancode.SCANCODE_END | (1 << 30),
        PAGEDOWN = Scancode.SCANCODE_PAGEDOWN | (1 << 30),
        RIGHT = Scancode.SCANCODE_RIGHT | (1 << 30),
        LEFT = Scancode.SCANCODE_LEFT | (1 << 30),
        DOWN = Scancode.SCANCODE_DOWN | (1 << 30),
        UP = Scancode.SCANCODE_UP | (1 << 30),

        NUMLOCKCLEAR = Scancode.SCANCODE_NUMLOCKCLEAR | (1 << 30),
        KP_DIVIDE = Scancode.SCANCODE_KP_DIVIDE | (1 << 30),
        KP_MULTIPLY = Scancode.SCANCODE_KP_MULTIPLY | (1 << 30),
        KP_MINUS = Scancode.SCANCODE_KP_MINUS | (1 << 30),
        KP_PLUS = Scancode.SCANCODE_KP_PLUS | (1 << 30),
        KP_ENTER = Scancode.SCANCODE_KP_ENTER | (1 << 30),
        KP_1 = Scancode.SCANCODE_KP_1 | (1 << 30),
        KP_2 = Scancode.SCANCODE_KP_2 | (1 << 30),
        KP_3 = Scancode.SCANCODE_KP_3 | (1 << 30),
        KP_4 = Scancode.SCANCODE_KP_4 | (1 << 30),
        KP_5 = Scancode.SCANCODE_KP_5 | (1 << 30),
        KP_6 = Scancode.SCANCODE_KP_6 | (1 << 30),
        KP_7 = Scancode.SCANCODE_KP_7 | (1 << 30),
        KP_8 = Scancode.SCANCODE_KP_8 | (1 << 30),
        KP_9 = Scancode.SCANCODE_KP_9 | (1 << 30),
        KP_0 = Scancode.SCANCODE_KP_0 | (1 << 30),
        KP_PERIOD = Scancode.SCANCODE_KP_PERIOD | (1 << 30),

        APPLICATION = Scancode.SCANCODE_APPLICATION | (1 << 30),
        POWER = Scancode.SCANCODE_POWER | (1 << 30),
        KP_EQUALS = Scancode.SCANCODE_KP_EQUALS | (1 << 30),
        F13 = Scancode.SCANCODE_F13 | (1 << 30),
        F14 = Scancode.SCANCODE_F14 | (1 << 30),
        F15 = Scancode.SCANCODE_F15 | (1 << 30),
        F16 = Scancode.SCANCODE_F16 | (1 << 30),
        F17 = Scancode.SCANCODE_F17 | (1 << 30),
        F18 = Scancode.SCANCODE_F18 | (1 << 30),
        F19 = Scancode.SCANCODE_F19 | (1 << 30),
        F20 = Scancode.SCANCODE_F20 | (1 << 30),
        F21 = Scancode.SCANCODE_F21 | (1 << 30),
        F22 = Scancode.SCANCODE_F22 | (1 << 30),
        F23 = Scancode.SCANCODE_F23 | (1 << 30),
        F24 = Scancode.SCANCODE_F24 | (1 << 30),
        EXECUTE = Scancode.SCANCODE_EXECUTE | (1 << 30),
        HELP = Scancode.SCANCODE_HELP | (1 << 30),
        MENU = Scancode.SCANCODE_MENU | (1 << 30),
        SELECT = Scancode.SCANCODE_SELECT | (1 << 30),
        STOP = Scancode.SCANCODE_STOP | (1 << 30),
        AGAIN = Scancode.SCANCODE_AGAIN | (1 << 30),
        UNDO = Scancode.SCANCODE_UNDO | (1 << 30),
        CUT = Scancode.SCANCODE_CUT | (1 << 30),
        COPY = Scancode.SCANCODE_COPY | (1 << 30),
        PASTE = Scancode.SCANCODE_PASTE | (1 << 30),
        FIND = Scancode.SCANCODE_FIND | (1 << 30),
        MUTE = Scancode.SCANCODE_MUTE | (1 << 30),
        VOLUMEUP = Scancode.SCANCODE_VOLUMEUP | (1 << 30),
        VOLUMEDOWN = Scancode.SCANCODE_VOLUMEDOWN | (1 << 30),
        KP_COMMA = Scancode.SCANCODE_KP_COMMA | (1 << 30),
        KP_EQUALSAS400 =
            Scancode.SCANCODE_KP_EQUALSAS400 | (1 << 30),

        ALTERASE = Scancode.SCANCODE_ALTERASE | (1 << 30),
        SYSREQ = Scancode.SCANCODE_SYSREQ | (1 << 30),
        CANCEL = Scancode.SCANCODE_CANCEL | (1 << 30),
        CLEAR = Scancode.SCANCODE_CLEAR | (1 << 30),
        PRIOR = Scancode.SCANCODE_PRIOR | (1 << 30),
        RETURN2 = Scancode.SCANCODE_RETURN2 | (1 << 30),
        SEPARATOR = Scancode.SCANCODE_SEPARATOR | (1 << 30),
        OUT = Scancode.SCANCODE_OUT | (1 << 30),
        OPER = Scancode.SCANCODE_OPER | (1 << 30),
        CLEARAGAIN = Scancode.SCANCODE_CLEARAGAIN | (1 << 30),
        CRSEL = Scancode.SCANCODE_CRSEL | (1 << 30),
        EXSEL = Scancode.SCANCODE_EXSEL | (1 << 30),

        KP_00 = Scancode.SCANCODE_KP_00 | (1 << 30),
        KP_000 = Scancode.SCANCODE_KP_000 | (1 << 30),
        THOUSANDSSEPARATOR =
            Scancode.SCANCODE_THOUSANDSSEPARATOR | (1 << 30),
        DECIMALSEPARATOR =
            Scancode.SCANCODE_DECIMALSEPARATOR | (1 << 30),
        CURRENCYUNIT = Scancode.SCANCODE_CURRENCYUNIT | (1 << 30),
        CURRENCYSUBUNIT =
            Scancode.SCANCODE_CURRENCYSUBUNIT | (1 << 30),
        KP_LEFTPAREN = Scancode.SCANCODE_KP_LEFTPAREN | (1 << 30),
        KP_RIGHTPAREN = Scancode.SCANCODE_KP_RIGHTPAREN | (1 << 30),
        KP_LEFTBRACE = Scancode.SCANCODE_KP_LEFTBRACE | (1 << 30),
        KP_RIGHTBRACE = Scancode.SCANCODE_KP_RIGHTBRACE | (1 << 30),
        KP_TAB = Scancode.SCANCODE_KP_TAB | (1 << 30),
        KP_BACKSPACE = Scancode.SCANCODE_KP_BACKSPACE | (1 << 30),
        KP_A = Scancode.SCANCODE_KP_A | (1 << 30),
        KP_B = Scancode.SCANCODE_KP_B | (1 << 30),
        KP_C = Scancode.SCANCODE_KP_C | (1 << 30),
        KP_D = Scancode.SCANCODE_KP_D | (1 << 30),
        KP_E = Scancode.SCANCODE_KP_E | (1 << 30),
        KP_F = Scancode.SCANCODE_KP_F | (1 << 30),
        KP_XOR = Scancode.SCANCODE_KP_XOR | (1 << 30),
        KP_POWER = Scancode.SCANCODE_KP_POWER | (1 << 30),
        KP_PERCENT = Scancode.SCANCODE_KP_PERCENT | (1 << 30),
        KP_LESS = Scancode.SCANCODE_KP_LESS | (1 << 30),
        KP_GREATER = Scancode.SCANCODE_KP_GREATER | (1 << 30),
        KP_AMPERSAND = Scancode.SCANCODE_KP_AMPERSAND | (1 << 30),
        KP_DBLAMPERSAND =
            Scancode.SCANCODE_KP_DBLAMPERSAND | (1 << 30),
        KP_VERTICALBAR =
            Scancode.SCANCODE_KP_VERTICALBAR | (1 << 30),
        KP_DBLVERTICALBAR =
            Scancode.SCANCODE_KP_DBLVERTICALBAR | (1 << 30),
        KP_COLON = Scancode.SCANCODE_KP_COLON | (1 << 30),
        KP_HASH = Scancode.SCANCODE_KP_HASH | (1 << 30),
        KP_SPACE = Scancode.SCANCODE_KP_SPACE | (1 << 30),
        KP_AT = Scancode.SCANCODE_KP_AT | (1 << 30),
        KP_EXCLAM = Scancode.SCANCODE_KP_EXCLAM | (1 << 30),
        KP_MEMSTORE = Scancode.SCANCODE_KP_MEMSTORE | (1 << 30),
        KP_MEMRECALL = Scancode.SCANCODE_KP_MEMRECALL | (1 << 30),
        KP_MEMCLEAR = Scancode.SCANCODE_KP_MEMCLEAR | (1 << 30),
        KP_MEMADD = Scancode.SCANCODE_KP_MEMADD | (1 << 30),
        KP_MEMSUBTRACT =
            Scancode.SCANCODE_KP_MEMSUBTRACT | (1 << 30),
        KP_MEMMULTIPLY =
            Scancode.SCANCODE_KP_MEMMULTIPLY | (1 << 30),
        KP_MEMDIVIDE = Scancode.SCANCODE_KP_MEMDIVIDE | (1 << 30),
        KP_PLUSMINUS = Scancode.SCANCODE_KP_PLUSMINUS | (1 << 30),
        KP_CLEAR = Scancode.SCANCODE_KP_CLEAR | (1 << 30),
        KP_CLEARENTRY = Scancode.SCANCODE_KP_CLEARENTRY | (1 << 30),
        KP_BINARY = Scancode.SCANCODE_KP_BINARY | (1 << 30),
        KP_OCTAL = Scancode.SCANCODE_KP_OCTAL | (1 << 30),
        KP_DECIMAL = Scancode.SCANCODE_KP_DECIMAL | (1 << 30),
        KP_HEXADECIMAL =
            Scancode.SCANCODE_KP_HEXADECIMAL | (1 << 30),

        LCTRL = Scancode.SCANCODE_LCTRL | (1 << 30),
        LSHIFT = Scancode.SCANCODE_LSHIFT | (1 << 30),
        LALT = Scancode.SCANCODE_LALT | (1 << 30),
        LGUI = Scancode.SCANCODE_LGUI | (1 << 30),
        RCTRL = Scancode.SCANCODE_RCTRL | (1 << 30),
        RSHIFT = Scancode.SCANCODE_RSHIFT | (1 << 30),
        RALT = Scancode.SCANCODE_RALT | (1 << 30),
        RGUI = Scancode.SCANCODE_RGUI | (1 << 30),

        MODE = Scancode.SCANCODE_MODE | (1 << 30),

        AUDIONEXT = Scancode.SCANCODE_AUDIONEXT | (1 << 30),
        AUDIOPREV = Scancode.SCANCODE_AUDIOPREV | (1 << 30),
        AUDIOSTOP = Scancode.SCANCODE_AUDIOSTOP | (1 << 30),
        AUDIOPLAY = Scancode.SCANCODE_AUDIOPLAY | (1 << 30),
        AUDIOMUTE = Scancode.SCANCODE_AUDIOMUTE | (1 << 30),
        MEDIASELECT = Scancode.SCANCODE_MEDIASELECT | (1 << 30),
        WWW = Scancode.SCANCODE_WWW | (1 << 30),
        MAIL = Scancode.SCANCODE_MAIL | (1 << 30),
        CALCULATOR = Scancode.SCANCODE_CALCULATOR | (1 << 30),
        COMPUTER = Scancode.SCANCODE_COMPUTER | (1 << 30),
        AC_SEARCH = Scancode.SCANCODE_AC_SEARCH | (1 << 30),
        AC_HOME = Scancode.SCANCODE_AC_HOME | (1 << 30),
        AC_BACK = Scancode.SCANCODE_AC_BACK | (1 << 30),
        AC_FORWARD = Scancode.SCANCODE_AC_FORWARD | (1 << 30),
        AC_STOP = Scancode.SCANCODE_AC_STOP | (1 << 30),
        AC_REFRESH = Scancode.SCANCODE_AC_REFRESH | (1 << 30),
        AC_BOOKMARKS = Scancode.SCANCODE_AC_BOOKMARKS | (1 << 30),

        BRIGHTNESSDOWN =
            Scancode.SCANCODE_BRIGHTNESSDOWN | (1 << 30),
        BRIGHTNESSUP = Scancode.SCANCODE_BRIGHTNESSUP | (1 << 30),
        DISPLAYSWITCH = Scancode.SCANCODE_DISPLAYSWITCH | (1 << 30),
        KBDILLUMTOGGLE =
            Scancode.SCANCODE_KBDILLUMTOGGLE | (1 << 30),
        KBDILLUMDOWN = Scancode.SCANCODE_KBDILLUMDOWN | (1 << 30),
        KBDILLUMUP = Scancode.SCANCODE_KBDILLUMUP | (1 << 30),
        EJECT = Scancode.SCANCODE_EJECT | (1 << 30),
        SLEEP = Scancode.SCANCODE_SLEEP | (1 << 30)
    }

    /// <summary>
    /// Enumeration of valid key mods (possibly OR'd together).
    /// </summary>
    [Flags]
    public enum Keymod
    {
        None = 0x0000,
        LeftShift = 0x0001,
        RightShift = 0x0002,
        LeftControl = 0x0040,
        RightControl = 0x0080,
        LeftAlt = 0x0100,
        RightAlt = 0x0200,
        LeftGui = 0x0400,
        RightGui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Reserved = 0x8000
    }
}
